package com.church.qt.common;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;

@Component
@RequiredArgsConstructor
public class AuditLogSchemaInitializer {

    private final DataSource dataSource;
    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void initialize() {
        jdbcTemplate.execute(buildCreateTableSql());
    }

    private String buildCreateTableSql() {
        String identityDefinition = resolveIdentityDefinition();
        return """
                create table if not exists audit_logs (
                    id bigint %s primary key,
                    actor_teacher_id bigint,
                    action_type varchar(100),
                    detail varchar(1000),
                    created_at timestamp default current_timestamp
                )
                """.formatted(identityDefinition);
    }

    private String resolveIdentityDefinition() {
        try (Connection connection = dataSource.getConnection()) {
            String databaseProductName = connection.getMetaData().getDatabaseProductName();
            if (databaseProductName != null && databaseProductName.toLowerCase().contains("mysql")) {
                return "auto_increment";
            }
            return "generated by default as identity";
        } catch (SQLException e) {
            throw new IllegalStateException("audit_logs 테이블 초기화용 DB 정보를 확인할 수 없습니다.", e);
        }
    }
}
